dist: xenial
language: python
cache: pip

branches:
  only:
    - master

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

before_install:
  - pip install --upgrade pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install: poetry install

script: pytest tests/ --cov=modbot
