dist: xenial
language: python
cache: pip

branches:
  only:
    - master

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

before_install:
  - pip install --upgrade pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install: poetry install

before_script: pip install codecov

script: pytest tests/ --cov=modbot

after_success: codecov

notifications:
  slack:
    rooms:
      secure: QmJJuCQu048BWIoBJNbmnQXd4SwooWh8O1MCgYQ/ufXN0y4kaWrQXUd6MWm5Mwi3r0tqZyJqTIpGNOSj7/I31z4/7KHUnnuScsT2DGzdXFu5i4HUHasT+aFddO8au98XiMm/prThjU9Byylv/3cYo6WUttBNMTpLsCAntnLM8b8s5b78yBdecOafDQQUA/5UeH2QDNShIOPqTWo0EF80eSl2I5qVgyqBehs4ePoWaDjl+ZneydtmrMo+pM/qpjmv8sW95tk/IVeZGrVMpHrquX/L4IaKq6q0korpZD3QE4V5dhFsqQvmXhHaQ3Z9BgY4K6zbkRYIxjpKF2RCmp4GNr9xATez86RPKWFfll05Zr7h4geKUfi/Sk/3FKg2IMcTpGSn2zaggqk9yAWTxXJgi/kY7+slI02RtgEwwqhqZDkEPJ9Oc6dez1OXXRBn2ds4yas5B4Q422/M9lcRVMuyXPTr8OFRVBe2WBJOWnM9MM5xCgfYSklpUZPy2/Av2W/ASHsy8Eqh5e+62Yf9Ck1IJblEr/fZHEHG4q3Nw7vQV18jxz31QRoBQhbrvpDfvw1iYLqgsTl5u59DpDb9HntVOIPh59TPWNoM7rI2vQEd5qKaBoIX7HDaboW7HQ3RkuUM77WFtug1Hx/wA9PUqfoxUUD//lrNMD3nUO1a7nvnPP0=
