dist: xenial
language: python
cache: pip

branches:
  only:
    - master

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

before_install:
  - pip install --upgrade pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install: poetry install

before_script: pip install codecov

script: pytest tests/ --cov=modbot

after_success: codecov

notifications:
  slack:
    rooms:
      secure: WioJqeHM+LqNbWE1+cVfO/3FjD5DU5eYza9U17lGy5oi9GVK6Yfpe0dOFp0QUkjJ+RyqSvaPPI1KWRRBSt5ZsCH/ZYAm9zhzph7UMFoC2aLQdY7i8OppYT303Sl1qLX8jTXccxgdttsaRml5A2aFbzglTrwhoC2QkgF8byz2bCJ5HLRknJEeJWSJNAdUw673JVv4tu2A6ViZgZg4FZPS0XXExF8yHzPG39Dz9iLY5ekmbA2CfnUiw/jDgiRkUbbKjPI00Xlli1xtc23/zZgVcvlxvmDQ16785eGP2oNwpdNgJHBjEMDO8DEfu+ltxFdeb2HSo8BLVFIJt4U/yRDBXGf54z2nWLh+3zeIMaWMqsRAEGPqSRv5Pth5fA97CKUK0l3XctNjlHb+dFMlLShwElQ4/zpedEagytloSvciLPYSaVr9MqHhlRgWVjNDZ6ddgIcj+FwL4fVuEXyMmkb2D5H44OWGQ3k/zJmhsjrQxWOLbRgQ1JTcEGCSHi5WbbfqU93FPjDAo6QLeh+V9a52jPT1bf/5FAUeOlDF0g0MGqCmhdTjUwzo3g1QPAh4ukIvv2KQab+4IEyvAm5rFei4+LfcB+IMW0/LAX/UfeyvkcznWdpS+qL5ZA7M59pviaTtF97L7bi0Vv+xNbhB6wlaHjx9jBXIfLKDiTvADAFWl3I=
