dist: xenial
language: python
cache: pip

branches:
  only:
    - master

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

before_install:
  - pip install --upgrade pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install: poetry install

before_script: pip install codecov

script: pytest tests/ --cov=modbot

after_success: codecov

notifications:
  slack:
    rooms:
      secure: WuYhaGSuaFDfS2P25V7n4UF/gD+eUPv7v3NzitUlOsUEGHqZw/403VZUmkoQ3c65c1rjaZSzSgVdE8TFzlHDI6RYJcupHv041uNN/9ROwjpJK+msLAxJ0vt965detJuA8w23UyrhakRm+Y4P2peteIivOBLV/iphSWVKu7eDADF3pzGGBF5y49uDpGezMAgMuc1ekmK4Ly+XUkvRQsMNSmxt6OyEiiAKayUtgzpiVL7zaPzJ34xlt33dwE/OuuTHtCMtFit9Jdz+iemSZBitOlbz06AujvjrS9Fe4oWv79cZjL/OAuxiGdsJSoDeCBh5waJ1UQOfw8XKMsiotkT+hCKphIhVKbNW3XWxohHt2HRfA7enD8DSgbzJeGH++XC+zDtXSlNBg2tXCFFmsS/0wyX1eo1BB5f1E9SvBnr/vhEQizI1q8rZEO43CHHFg4faGn0yYuKcPuAGDJliNwMD6Tt5c7cGwRBIJPLqhjHfzq6Z7kR8QYvGAshc60d1nrqcprb2banxjZFrXFF9PTW92N2EAlZDilCRMBk+RaPzDtJH8AHMKFDzC01zh607JMevi9lVTMwTGe1YGbJ1sl+2jGgl93WiaLXQidJ1TL5tEvaNugFe7dCrZmNaB9paKBmiyrF44blQkQ6BDbovbo2SKcigTHhGb2csaxLtoM2jL7U=
