[tool.poetry]
name = "dotbot-add"
version = "0.1.0"
description = "Track new dotfiles and link them with Dotbot"
authors = ["Kevin Lane <lane.kevin.a@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/klane/dotbot-add"

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
dotbot = "^1.14"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
