name: Tests

on: push

jobs:
  Safety:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - name: Install Safety
        run: |
          pip install safety
      - name: Check dependencies
        run: |
          source $HOME/.poetry/env
          poetry show -a | sed 's/(!)//' | awk '{print $1,"==",$2}' | safety check --stdin

  Linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install-hooks
      - name: Run hooks
        run: |
          pre-commit run --all-files

  test:
    name: "${{ matrix.os_name }}: Python ${{ matrix.python }}"
    needs: [Safety, Linting]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [2.7, 3.5, 3.6, 3.7]
        include:
          - os: ubuntu-latest
            os_name: Linux
            path: ~/.poetry/bin
            cache: ~/.cache/pypoetry
          - os: macos-latest
            os_name: macOS
            path: ~/.poetry/bin
            cache: ~/Library/Caches/pypoetry
          - os: windows-latest
            os_name: Windows
            path: $env:Userprofile\.poetry\bin
            cache: ~\AppData\Local\pypoetry\Cache

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
          echo "::add-path::${{ matrix.path }}"
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ${{ matrix.cache }}
          key: ${{ runner.os }}-python${{ matrix.python }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-python${{ matrix.python }}-poetry-
      - name: Install dependencies
        run: |
          poetry install
      - name: Runs tests
        run: |
          poetry run pytest tests/ --cov=modbot
          poetry run coverage xml
      - name: Upload coverage report
        if: success()
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
